services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 24042003
      MYSQL_DATABASE: med_pro_database
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 24042003
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  mysql_data:
